let mongoose = require('mongoose');

let studentSchema = new mongoose.Schema({

    studentId: Number,     //assigned by us? This should be autogenerated.
    firstName:String,
    lastName: String,
    dateOfBirth: {type:Date},
    gender: String,
    email: String,
    grade: String,
    status: String,
    relatives: [{ type : mongoose.Schema.ObjectId, ref : 'relative' }]
});


module.exports = mongoose.model('Student', studentSchema);